version: '3.8'

services:
  products-nextjs:
    build:
      context: ./products-nextjs
      dockerfile: Dockerfile
    ports:
      - "3000:3000"  # Next.js app on port 3000
    environment:
      - API_AUTH_KEY=qwerty123  # Pass the environment variable for Next.js

  basket-react:
    build:
      context: ./basket-react # Assuming this is the directory for your new React + Vite app
      dockerfile: Dockerfile
    ports:
      - "3002:80"  # Map container's 80 to host's 3002
    environment:
      - VITE_API_URL=http://localhost:3000/api
      - VITE_API_KEY=qwerty123