import "@ant-design/v5-patch-for-react-19"
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../lib/styles/globals.css";
import type React from "react"
import { ConfigProvider, App as AntApp } from "antd";
import { Providers } from "@/lib/providers";
import Navbar from "@/components/navbar";
import Footer from "@/components/layout/Footer";
import ClientErrorBoundary from "@/components/ClientErrorBoundary";
import { AuthProvider } from "@/lib/hooks/useAuth";
import SiteFooter from "@/components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <ConfigProvider
            theme={{
              token: {
                colorPrimary: "#1677ff",
              },
            }}
          >
            <AntApp>
              <AuthProvider>
                <ClientErrorBoundary>
                  <Navbar />
                  {children}
                  <SiteFooter />
                </ClientErrorBoundary>
              </AuthProvider>
            </AntApp>
          </ConfigProvider>
        </Providers>
      </body>
    </html>
  );
}